### PR TITLE
"@Elix remind me to finish this PR in 1 week"

### LINKED ISSUE #7: Have elix remind people about things
### Example API

```
Steve: @Elix remind me to check the thing in an hour
Elix: Okay, @Steve. In one hour I'll remind you to check the thing
... 1 hour later
Elix: @Steve, you asked me to remind you to check the thing now.
```

### Features

- natural-language alternatives (always start with "remind me" though), e.g.
  - remind me to X in TIME
  - remind me in TIME to X
  - remind me about X in TIME
  - remind me of X in time
- relative and absolute times, "in 3 hours" vs. "at 9am tomorrow"
  - [timex](https://github.com/bitwalker/timex/#quickfast-introduction) does relative times
- show all scheduled reminders with the ability to cancel?

### Technical

- actually, this gets real tricky: how do we get Hedwig to send a spontaneous message?
- probably means we'll need a time zone in the environment
- we could do this pretty trivially with [`Process.send_after/3`](http://elixir-lang.org/docs/stable/elixir/Process.html#send_after/3) but if the process crashed we'll lose all the pending reminders. Probably want to store these in Redis keyed to the reminder date/time and query them every second or something.

### PR DESCRIPTION
**Pull request by stevegrossi**
Resolves #7

### CODE REVIEW

File: lib/elix/reminder.ex [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+         end)
+      |> Enum.reject(&is_nil/1)
+
+    heartbeat() # Keep beating
+    {:noreply, new_state}
+  end
+
+  defp heartbeat() do
+    Process.send_after(self(), :heartbeat, 1_000)
+  end
```
Comment (stevegrossi) [inline lib/elix/reminder.ex]: Thanks, José! http://stackoverflow.com/a/32097971/995663

File: lib/elix/reminder.ex [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+      state
+      |> Enum.map(fn ({message, timestamp, msg} = reminder) ->
+           if timestamp < :os.system_time(:seconds) do
+             GenServer.cast(msg.robot, {:reply, %{msg | text: message}})
+             nil
+           else
+             reminder
+           end
+         end)
+      |> Enum.reject(&is_nil/1)
```
Comment (stevegrossi) [inline lib/elix/reminder.ex]: Just a proof-of-concept, but proof!



Eventually this should be an ordered set in Redis so all the reminders aren't forgotten if the process is restarted, but structs and `pid`s can't be stored in Redis so that'll be a challenge.

File: test/message_scheduler_test.exs [hunk 3]
```diff
@@ -0,0 +1,14 @@
+defmodule Elix.MessageSchedulerTest do
+  use ExUnit.Case
+  doctest Elix.MessageScheduler
+
+  test "sends a message" do
+    assert Elix.MessageScheduler.send_at(now(), :test) == :ok
+
+    # Actually testing this module will be a challenge...
```
Comment (stevegrossi) [inline test/message_scheduler_test.exs]: Part of the trouble is that `assert_receive` asserts that a message was received by _the current process_, which is the test itself in this context. `Elix.MessageScheduler` is hard-coded to send messages to `Elix.Robot`. I could perhaps allow configuring the recipient to `Elix.TestRobot` in tests and registering this test process under that name at the start...

File: test/responders/lists_test.exs [hunk 4]
```diff
@@ -224,44 +222,36 @@ defmodule Elix.Responders.ListsTest do
...
     end
   end
-
-  defp to_bot(text) when is_binary(text) do
-    @bot_name <> " " <> text
-  end
-
-  defp to_user(string) when is_binary(string) do
-    @user_name <> ": " <> string
-  end
```
Comment (stevegrossi) [inline test/responders/lists_test.exs]: Whoops, this should not be part of this PR.

File: test/message_scheduler_test.exs (hunk 3 above)
Comment (stevegrossi) [reply test/message_scheduler_test.exs]: Also, `Elix.MessageScheduler` assumes the recipient will be a `GenServer`, which the test process is not. So I'd perhaps need a simpler GenServer forwarder process to receive messages and forward them to the test process.

**Comment by stevegrossi** [comment]
So what's holding this up is that:

1. In order to send a reminder message possibly days after it was enqueued and the Hedig robot process's `pid` may have changed, I need to register the robot's process by name
2. That requires a callback only available in the latest version of Hedwig
3. The current version of `hedwig_flowdock` adapter doesn't yet support the latest version of Hedwig (which was a fairly significant rewrite)

So I'm looking at [submitting a PR](https://github.com/supernullset/hedwig_flowdock/pull/8) to fix `hedwig_flowdock` for the latest version of Hedwig in order to move this PR forward...

**Comment by stevegrossi** [comment]
https://github.com/stevegrossi/hedwig_flowdock fixed—now to finally get this merged!

**Comment by stevegrossi** [comment]
Hm, I got this working beautifully in the console, but it isn't working on Flowdock. I've narrowed it down to the fact that the custom `handle_connect` callback I'm providing isn't being called when used with the Flowdock adapter, so the process never gets registered:

```elixir
def handle_connect(state) do
  IO.puts("Handling connect")
  if is_nil(Process.whereis(__MODULE__)) do
    true = Process.register(self(), __MODULE__)
  end
  {:ok, state}
end
```

**Comment by stevegrossi** [comment]
...and it looks like another (unmentioned, unfortunately) Hedwin 1.0 deprecation. Hedwig 1.0 is sending a `:connected` message, but hedwig_flowdock is expecting `:connection_ready` which may have been a previous version. Gonna test that.

Alas, it's not quite that simple. After copying hedwig's current implementation of the connection handler:

```elixir
def handle_info(:connected, %{robot: robot} = state) do
  :ok = Hedwig.Robot.handle_connect(robot)
  {:noreply, state}
end
```

in place of hedwig_flowdock's:

```elixir
def handle_info(:connection_ready, %{robot: robot} = state) do
  Hedwig.Robot.handle_connect(robot)
  {:noreply, state}
end
```

isn't enough to fix it.

**Comment by stevegrossi** [comment]
And fixed! https://github.com/supernullset/hedwig_flowdock/pull/8/commits/61bed3b8db0bf20d745efee51971a24f3479cda9 This is tested and good to go!

screen shot 2017-01-15 at 1 06 40 pm
